"""create_states_table

Revision ID: 12824e5c484c
Revises: 6a97e8f3dde0
Create Date: 2025-10-12 08:14:16.886107

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12824e5c484c"
down_revision: str | Sequence[str] | None = "6a97e8f3dde0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"], ["main.countries.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="main",
    )
    op.create_index("idx_states_country_id", "states", ["country_id"], schema="main")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_states_country_id", table_name="states", schema="main")
    op.drop_table("states", schema="main")
    # ### end Alembic commands ###
