"""add cities table

Revision ID: ea788c0b8b4a
Revises: 12824e5c484c
Create Date: 2025-11-09 09:01:13.867056

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea788c0b8b4a"
down_revision: str | Sequence[str] | None = "12824e5c484c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("state_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["state_id"], ["main.states.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )

    # Create conditional unique index: code is unique only when is_active = true
    op.create_index(
        "cities_code_active_unique",
        "cities",
        ["code"],
        unique=True,
        schema="main",
        postgresql_where=sa.text("is_active = true"),
    )

    # Create index on state_id for faster foreign key lookups
    op.create_index("idx_cities_state_id", "cities", ["state_id"], schema="main")

    # Create index on is_active for filtering queries
    op.create_index("idx_cities_is_active", "cities", ["is_active"], schema="main")

    op.drop_index(op.f("idx_event_logs_entity"), table_name="event_logs", schema="main")
    op.drop_index(
        op.f("idx_event_logs_processing"), table_name="event_logs", schema="main"
    )
    op.drop_index(op.f("idx_states_country_id"), table_name="states", schema="main")
    op.drop_constraint(
        op.f("states_country_id_fkey"), "states", schema="main", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("states_country_id_fkey"),
        "states",
        "countries",
        ["country_id"],
        ["id"],
        source_schema="main",
        referent_schema="main",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("states_country_id_fkey"), "states", schema="main", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("states_country_id_fkey"),
        "states",
        "countries",
        ["country_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        op.f("idx_states_country_id"), "states", ["country_id"], unique=False
    )
    op.create_index(
        op.f("idx_event_logs_processing"),
        "event_logs",
        ["processing_status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_logs_entity"),
        "event_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )

    # Drop indexes on cities table
    op.drop_index("idx_cities_is_active", table_name="cities", schema="main")
    op.drop_index("idx_cities_state_id", table_name="cities", schema="main")
    op.drop_index("cities_code_active_unique", table_name="cities", schema="main")

    # Drop cities table
    op.drop_table("cities", schema="main")
    # ### end Alembic commands ###
